version: "3.9"
services:
  api:
    image: api
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./api:/app/api
