// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InMemoryRepository is an autogenerated mock type for the InMemoryRepository type
type InMemoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *InMemoryRepository) Create(_a0 string, _a1 interface{}) {
	_m.Called(_a0, _a1)
}

// Exist provides a mock function with given fields: _a0
func (_m *InMemoryRepository) Exist(_a0 string) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields: _a0
func (_m *InMemoryRepository) Get(_a0 string) interface{} {
	ret := _m.Called(_a0)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
